### ISSUE TITLE
Play Store

### ISSUE THREAD

**Issue by jrpetersjr** [florianmski/Traktoid#10]
You do realize it got pulled from the Play Store because you didn't blur the pictures on the play store page. For instance look at seriesguide
![screen shot 2015-06-12 at 4 06 41 am](https://cloud.githubusercontent.com/assets/9285616/8125969/7b294d7c-10b8-11e5-8a6b-9b26c634e37d.png)

**Comment by jrpetersjr** [comment]
That's all you would have to do to get back on the play store.

**Comment by florianmski** [comment]
Yep, I know.
It'll be back on the Playstore when I'll find some time.
