### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by pizzamaker** [florianmski/Traktoid#13]
It would be cool if this application made its way into F-Droid https://f-droid.org/

Here's how to: https://f-droid.org/contribute/

**Comment by alexanderadam** [comment]
Any reason why this issue was closed?

I can't find it [on F-Droid yet](https://staging.f-droid.org/search?q=traktoid&lang=de).

**Comment by florianmski** [comment]
Am not sure, was over two years ago 😃
But the app has not been updated for ages, probably is crashing due to loads of changes on the Trakt API side of things unfortunately :/
