### ISSUE TITLE
Unable to open the applicaton with Android Studio.

### ISSUE THREAD

**Issue by JesusValeraDev** [florianmski/Traktoid#15]
Gradle told me: "Error: Configuration with name 'default' not found".
I've tried to find solution in stackoverflow but I only found a page which a guy said that I should move the libs folder into root directory but it doesn't work (or I think so).
The problem looks like the lib "trakt-java-git".
If I comment the dependency "compile project(':trakt-java-git')" from /app/build.gradle the project compilation works.

**Comment by florianmski** [comment]
Hey Jesus,

Please have a look over there #12 
Someone had the same issue.

Unfortunately I didn't touch this project in 2 years and I haven't be good at making it easily forkable as there's quite some internal dependencies which is pretty bad...

Furthermore, there was a lot of changes on Trakt side concerning APIs and also they don't serve images anymore (see #14 )

This project would probably beneficit for a partial / full rewrite but that is not something I can afford at the moment 😞
