### ISSUE TITLE
Search Doesn't Allow Checkin

### ISSUE THREAD

**Issue by unrulybeep** [florianmski/Traktoid#3]
Perhaps I am misunderstanding the intention here. When I search for something, it comes up no problem. However, as far as I can tell, only the show description, rating, and a pic is shown. I see no way to go into the show in order to check in, look at the seasons, etc.

I checked into the show via the trakt website, since I couldn't figure out how to do it via traktoid, and I saw the "you're watching" banner. Which I love. However, I have to go into the library section and then click on the show to be able to get to the area where I can checkin, view episodes, view seasons etc. What do I do when I haven't watched a show before?

**Comment by florianmski** [comment]
see #8
