### ISSUE TITLE
Back navigation from action bar (show-->main screen) doesn't work

### ISSUE THREAD

**Issue by AndyScherzinger** [florianmski/Traktoid#7]
In case I am on the show screen I can hit the back button from the standard bottom actions but the back action in the action bar at the top doesn't trigger a back navigation.

**Comment by florianmski** [comment]
I'm aware, you can see bugs and missing features here: https://trello.com/b/cCln8x5J/traktoid

**Comment by AndyScherzinger** [comment]
Thanks for the hint. So should bug be posted via trello then?

**Comment by florianmski** [comment]
Just make sure it's not already on Trello and post in the "Bugs" section on the g+ community so we can talk about it, thanks :+1:

**Comment by florianmski** [comment]
Implemented a "naive" up navigation 77d5362afc31019143d280b29377dbb13c1d6079
I need to figure out how to handle case where an activity has multiple possible parents or a parent needs data to work correctly.
